openapi: 3.0.3
info:
  title: Payment Routing Service
  version: 1.3.0
paths:
  /payment-routing/resolve:
    post:
      summary: Resolve correspondent bank routing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoutingRequest'
      responses:
        '200':
          description: Evaluation result including GREEN/RED routes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutingResponse'
components:
  schemas:
    RoutingRequest:
      type: object
      properties:
        ruleContext:
          type: object
          properties:
            payment:
              type: object
              properties:
                direction:
                  type: string
                currency:
                  type: string
                chargeBearer:
                  type: string
                  description: "BEN, SHA, OUR (OWN accepted and normalized to OUR)"
            counterparty:
              type: object
              properties:
                bankCountryCode:
                  type: string
                bankBic:
                  type: string
                account:
                  type: string
                name:
                  type: string
                type:
                  type: string
            customer:
              type: object
              properties:
                id: { type: string }
                industry: { type: string }
                type: { type: string }
                account: { type: string }
    RoutingResponse:
      type: object
      properties:
        status:
          type: string
          enum: [EVALUATED, NO_MATCH]
        decision:
          type: string
          enum: [CAN_ROUTE, CAN_NOT_ROUTE]
        greenRoutes:
          type: array
          items:
            $ref: '#/components/schemas/GreenRoute'
        redRoutes:
          type: array
          items:
            $ref: '#/components/schemas/RedRoute'
    GreenRoute:
      type: object
      properties:
        ruleCode: { type: string }
        corrBankBic: { type: string }
        description: { type: string }
        currency: { type: string, description: 'Payment currency (echo)'}
        chargeBearer: { type: string, description: 'Charge bearer (echo after normalization)'}
        nostroIban: { type: string, description: 'Corridor Nostro IBAN for currency if supported' }
    RedRoute:
      type: object
      properties:
        ruleCode: { type: string }
        corrBankBic: { type: string }
        description: { type: string }
